// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using erik_tech.Models;

namespace erik_tech.Migrations
{
    [DbContext(typeof(DbContextApp))]
    partial class DbContextAppModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7");

            modelBuilder.Entity("erik_tech.Models.Articulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Android")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Desarrollo")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Gaming")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Hardware")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Linux")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Macos")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Otra")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Windows")
                        .HasColumnType("INTEGER");

                    b.Property<int>("autor_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("cuerpo")
                        .HasColumnType("TEXT");

                    b.Property<string>("encabezado")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("fecha_publicacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("titulo_publicacion")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("articulo");
                });

            modelBuilder.Entity("erik_tech.Models.Cuenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("email")
                        .HasColumnType("TEXT");

                    b.Property<bool>("modoOscuro")
                        .HasColumnType("INTEGER");

                    b.Property<string>("parrafoDescripcion")
                        .HasColumnType("TEXT");

                    b.Property<string>("password")
                        .HasColumnType("TEXT");

                    b.Property<int>("temaColor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("urlImagenPerfil")
                        .HasColumnType("TEXT");

                    b.Property<string>("username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("cuenta");
                });

            modelBuilder.Entity("erik_tech.Models.comentario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Texto")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Comentarios");
                });

            modelBuilder.Entity("erik_tech.Models.urlImagen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdUser")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("externa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("nombre")
                        .HasColumnType("TEXT");

                    b.Property<string>("url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Imagenes");
                });
#pragma warning restore 612, 618
        }
    }
}
